### ISSUE TITLE
question(comparison): why htmlclean better, than alternatives?

### ISSUE THREAD

**Issue by Kristinita** [anseki/htmlclean#11]
### 1. Summary

In header.

### 2. Details

I'm a Grunt user. I find also 2 plugins for HTML minify:

+ [**grunt-minify-html**](https://www.npmjs.com/package/grunt-minify-html)
+ [**grunt-contrib-htmlmin**](https://www.npmjs.com/package/grunt-contrib-htmlmin)

Why I need use grunt-htmlclean, not these plugins? Any advantages, arguments, tests?

### 3. Examples in other apps

grunt-minify-html description:

> This differs from [**grunt-contrib-htmlmin**](https://github.com/gruntjs/grunt-contrib-htmlmin) in that it uses a proper [**HTML-parser**](https://github.com/Moveo/minimize#credits) instead of a [**bunch of fragile regexes**](https://github.com/kangax/html-minifier/blob/27fce5b5a7c166ea6149fba78a418e475658f075/src/htmlparser.js#L35-L41).

Thanks.

**Comment by anseki** [comment]
Hi @Kristinita, thank you for the comment.

htmlclean is very simple, and it is safety because it never changes HTML/SVG structure.
[HtmlCompressor](http://code.google.com/p/htmlcompressor/), [HTMLMinifier](https://github.com/kangax/html-minifier) and others are better choice if you want to control details of editing.
Those configuring are a little pain in the neck for me. And the results was not what I need.
So, I wrote htmlclean. This removes unneeded whitespaces, line-breaks, comments, etc. That's all. This doesn't parse syntax of HTML/SVG.

An important point, you should consider what the plugin uses to minify HTML/SVG.

+ grunt-minify-html uses [HTML minifier](https://github.com/Swaagie/minimize).
+ grunt-contrib-htmlmin uses [HTMLMinifier](https://github.com/kangax/html-minifier).

**Comment by anseki** [comment]
No reply came. I close this issue. :cry:
