### ISSUE TITLE
Add in a param to leave SVGs alone, as compression breaks already optimised SVGs

### ISSUE THREAD

**Issue by zizther** [anseki/htmlclean#14]
I have noticed recently when compressing my templates with optimised inline SVGs within them it will edit them and break the SVG icon.

Instead of me wrapping every inline SVG instance in `<!--[htmlclean-protect]-->` would it be possible to add in a param to leave SVG optimisations out?

As an example I have an arrow SVG
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 31.494 31.494">
    <path d="M10.273 5.009a1.112 1.112 0 011.587 0 1.12 1.12 0 010 1.571l-8.047 8.047h26.554c.619 0 1.127.492 1.127 1.111s-.508 1.127-1.127 1.127H3.813l8.047 8.032c.429.444.429 1.159 0 1.587a1.112 1.112 0 01-1.587 0L.321 16.532a1.12 1.12 0 010-1.571l9.952-9.952z"/>
</svg>
```

It would output this as
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 31.494 31.494">
    <path d="M10.273 5.009a1.112 1.112 0 11.587 0 1.12 1.12 0 10 1.571l-8.047 8.047h26.554c.619 0 1.127.492 1.127 1.111s-.508 1.127-1.127 1.127H3.813l8.047 8.032c.429.444.429 1.159 0 1.587a1.112 1.112 0 1-1.587 0L.321 16.532a1.12 1.12 0 10-1.571l9.952-9.952z"></path>
</svg>
```

**Comment by anseki** [comment]
Hi @zizther, thank you for the comment.
It seems that the path data in your first SVG was already broken.
The fourth argument `large-arc-flag` and fifth argument `sweep-flag` of `a` command have to be separated by comma or white space.
See document: https://www.w3.org/TR/2011/REC-SVG11-20110816/paths.html#PathDataBNF
That is, the path data has to be this even if the SVG is shown in your web browser luckily.
```svg
<path d="M10.273 5.009a1.112 1.112 0 0 1 1.587 0 1.12 1.12 0 0 1 0 1.571l-8.047 8.047h26.554c.619 0 1.127.492 1.127 1.111s-.508 1.127-1.127 1.127H3.813l8.047 8.032c.429.444.429 1.159 0 1.587a1.112 1.112 0 0 1-1.587 0L.321 16.532a1.12 1.12 0 0 1 0-1.571l9.952-9.952z"/>
```

After you fix the path data, the SVG that was cleaned should be shown fine.

**Comment by zizther** [comment]
@anseki Thanks for looking into this.
That is odd, the SVG has been optimised with SVGO before being used, which looks fine in the browser, but when additionally run through htmlclean it causes these issues.

I understand that SVGO is separate to htmlclean and it has its own params to control the output of the optimised SVG.
It would be good to try some different settings and see what the output would also be.

**Comment by anseki** [comment]
htmlclean can handle valid SVG and htmlclean doesn't break it. SVGO gives priority to the minifying rather than validity. Of course SVGO is great library to minify SVG.
Anyway, that broken SVG might be not shown correctly in some browser even if it is shown fine in your browser luckily.
That problem of SVGO is often being reported.
https://github.com/svg/svgo/issues?q=is%3Aissue+valid+OR+mess+OR+correct
For valid SVG, see document.
https://www.w3.org/TR/2011/REC-SVG11-20110816/paths.html#PathDataBNF
You will consider which of minifying (i.e. file size) or validity (i.e. safety) that you give priority to, and you can avoid SVGO changing the path data by disabling `convertPathData` plugin.
See document: https://github.com/svg/svgo

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
