### ISSUE TITLE
Recreate directory tree

### ISSUE THREAD

**Issue by mathpere** [anseki/htmlclean#5]
Hi,

This following command ```htmlclean src -o public``` only considers src/*.html files:

Would it possible to take care of ```src/**/*.html``` and recreate directory tree?

**Comment by anseki** [comment]
Hi mathpere.
Thank you for your post.
I agree to your proposal. It's useful.
But htmlclean must know where the root of directory tree is. New option might have to be added.
I think more about it.

**Comment by mathpere** [comment]
Thanks for your feedback. 
I don't understand why you would need new option.

For this given structure:

```
src
|--- index.html
|--- subfolder1
         |--- view1.html
         |--- view2.html
```

If I modify line 268 of htmlclean binary like this: 
```
pair(paths[0] + (paths[0].substr(-1) !== '/' ? '/' : '') + '/**/*.html', output);
```

I create dir destination: ```mkdir www ```

And I execute this command: ```htmlclean src -o public```

I get this structure:

```
www
|--- index.html
|--- view1.html
|--- view2.html
```

Could we use the exact same option by modifying the behavior when HTML files like view1.html, view2.html are not located at the root of src or am I wrong?

**Comment by anseki** [comment]
If you want only that behavior, htmlclean don't have to be modified. Just do `htmlclean "src/**/*.html" -o www`.

A `subfolder1` directory is missing in `www`.
"recreate directory tree" you said. That is, `subfolder1` must be made, right?

**Comment by anseki** [comment]
If the structure is:
```
src
|--- index.html
|--- subfolder1
|        |--- view1.html
|        |--- view2.html
|--- subfolder2
         |--- view1.html
         |--- view2.html
```
`view1.html` in `www` are mixed from `subfolder1/view1.html` and `subfolder2/view1.html`. `view2.html` too.

**Comment by mathpere** [comment]
Oh I'm sorry, my comment was not very clear.

By executing ```htmlclean src -o www``` I get this structure 
```
www
|--- index.html
|--- view1.html
|--- view2.html
```

But I would like
```
www
|--- index.html
|--- subfolder1
         |--- view1.html
         |--- view2.html
```

So I confirm: htmlclean should first automatically create ```subfolder1``` folder (e.g. [mkdirp] (https://github.com/substack/node-mkdirp))

**Comment by anseki** [comment]
Yes, therefore, I think new option have to be added.
htmlclean must know where the root of directory tree is. htmlclean must be given the root via new option, when it can't presume the root.
In your sample, a `subfolder1` directory missing in `www`. Then `mkdir subfolder1` is needed. It's very simple. because it is clear that `src` is root.
But, actually, the paths that is given might be not root, or the plurality of those are mixed, maybe.
For example:
* `src/content1/*.html` (I want to make `content1` directory in `www`.)
* `src/@(content1|content2)/*.html`
* `src{1,2}`
* `project1/src` (Don't make `src` directory in `www`.)

**Comment by anseki** [comment]
I rewrote. Please check new version 2.6.0.

The `--root` option was added.

* If you specify **one** root directory (even if it includes pattern) to input (like your sample), you have to do nothing. Because the specific directory is considered as the root.
* Note that if a directory is specified to the input, it is considered as `directory/**/*.html`. Not `directory/*.html`.

And, I close this issue. If there is problem, please reopen it.

**Comment by mathpere** [comment]
Not yet sure if this is an issue but when I execute this command:  ```htmlclean src  -o www```

I get this following error ``` Error: ENOENT, no such file or directory '' ```

**Comment by anseki** [comment]
Thank you for test.
Please check again in `verbose` mode.
```
htmlclean src -o www -v
```
And, permission of `www` is ok?

**Comment by anseki** [comment]
Sorry, I mistook...
I fixed it.
Please try v2.6.1.

**Comment by mathpere** [comment]
I tried version 2.6.2, it works like a charm, thank you!

**Comment by anseki** [comment]
Thank you for report :grinning:
