### ISSUE TITLE
extra space inserted after <div> followed by new line

### ISSUE THREAD

**Issue by henrysun918** [anseki/htmlclean#7]
Running htmlclean 2.7.7 on:
```
<div><a></a>x<span></span></div>
```

results in:
```
<div><a></a>x<span></span></div>
```

but running it on:
```
<div>
<a></a>x<span></span></div>
```
results in:
```
<div><a></a> x<span></span></div>
```

It looks like the "CR+LF" after `<div>` is translated into a space after `</a>`.

**Comment by anseki** [comment]
Hi @henrysun918, thank you for your post.

In HTML, all whitespace characters that include `CR`, `LF`, `TAB`, etc., are handled as spaces, and multiple whitespace characters are collapsed into a single space even if those include different characters, unless `white-space` property is specified. htmlclean handles those correctly, and it recognizes `pre` elements as `white-space: pre`.
And, htmlclean tries to reduce text-nodes in inline elements by checking text that needs whitespace as margin.
So, since the `<a>` element is empty inline, htmlclean recognizes that `x` needs whitespace at left.

```html
<div> <a></a>x<span></span></div>
```

Re:

```html
<div><a></a> x<span></span></div>
```

When the `<a>` element contains something:

```html
<div> <a>y</a>x<span></span></div>
```

Re:

```html
<div> <a>y</a>x<span></span></div>
```

**Comment by henrysun918** [comment]
Thanks for the quick reply @anseki. I see the rationale behind it. Normally I wouldn't have an empty `<a>` tag in the html but in this case, I'm using Angular framework that dynamically populates the innerHTML of the `<a>.` Would htmlclean() handle this use case? Or do I have to manually set the white-space property in CSS?

```
<div>
<a ng-bind="expression"></a>x<span></span></div>
```

**Comment by anseki** [comment]
You can use two ways to protect text.
https://github.com/anseki/htmlclean#protecting

* `htmlclean-protect` tags:

```html
<!--[htmlclean-protect]--><div> <a ng-bind="expression"></a>x<span></span></div><!--[/htmlclean-protect]-->
```

* `protect` option:

```js
htmlclean('<div> <a ng-bind="expression"></a>x<span></span></div>', {protect: /\s*<a ng-bind=[^>]*>[\s\S]*?<\/a>\s*/});
```

Result of two codes above:

```html
<div> <a ng-bind="expression"></a>x<span></span></div>
```

**Comment by henrysun918** [comment]
Thank you!

**Comment by yurks** [comment]
Technically this is correct. But usually developer take care about `white-space: pre` nodes by himself. Unlike stuff similar to
```
<div class="rating">
    <i></i>reviews
</div>
```
htmlclean will break visual design when transforming this into 
```
<div class="rating"><i></i> reviews</div>
```
with css like `i:after {content:'\icon'; padding-right:5px;}`

Adding option to strip whitespaces in front of blocks like "<div> <a>.." will be very useful for those people who use htmlclean to compress partial html templates.

**Comment by yurks** [comment]
A bit more thought :)
Instead _clean_ spaces htmlclean unobviously _add_ a new one in another place. 
Maybe leaving code like `<div> <a></a>x<span></span></div>` as it come will be carefully towards source html

**Comment by anseki** [comment]
Hi @yurks, thank you for your comment.

I understand you, but making htmlclean find those cases is not easy. Because web browsers and htmlclean can't distinguish needed whitespaces from meaningless whitespaces.
But I think that developers that know how web browsers handle whitespaces write whitespaces carefully. Then, web browsers and htmlclean can distinguish those.
For example, when we write "horizontal menu bar" without using `float`, `flex`, etc., we know that whitespaces break the layout using `inline`.

```css
.menu {
  padding: 0;
}

.menu>li {
  display: inline-block;
  background-color: #ccc;
}
```

```html
<ul class="menu">
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>
```

![s1](https://cloud.githubusercontent.com/assets/4763469/14452939/c5634cda-00cc-11e6-9060-67460fe73886.png)

We have to remove whitespaces or specify CSS property such as `font-size: 0` to remove unneeded margin between items.
Since developers know what to do, those will be not problem.

Other tools such as [HtmlCompressor](http://code.google.com/p/htmlcompressor/), [HTMLMinifier](https://github.com/kangax/html-minifier), etc., may help you.
Current htmlclean doesn't parse that JavaScript or CSS do something, it parse only HTML.
Of course I like other tools, but I wrote htmlclean because I wanted simple thing. Then I don't want to add more option to htmlclean.
But, as you said, an option to remove leading whitespaces in each blocks is useful. I might add that to a future version. Thank you.
