### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by trompx** [anseki/htmlclean#9]
Hello,

Maybe it is worth mentioning, I thought I had a bug.
I am using grunt-htmlclean 2.7.11 (which uses htmlclean 3.0.2) and had the following:

Input:
`<div class="aaa"><div>The <div class="bbb"><span class="xxx">Blabla</span></div></div>`

Output:
`<div class="aaa"><div>The<div class="bbb"><span class="xxx">Blabla</span></div></div>`

I thought it was a bug and believed the whitespace after `The` should have been be preserved. But then I guessed the `div tag` did not behave like the span tag which were the case, so after replacing my inline-block div by space, it worked.

Adding a not about this in the README could be great.

**Comment by trompx** [comment]
I have another case which is a bit annoying. I have the following:

Input:
```
<span><span>in </span><span class="dynamic"></span></span>
```

Output:
```
<span><span>in</span><span class="dynamic"></span></span>
```

I populate the `dynamic span` with javascript on user action, but as there is no html when htmlclean runs, the whitespace after `in` is removed.
What would you advice for that use case?

Another info, if I have php code between `<?php ... ?>` tags. After the php tag, the indentation is preserved (i.e. if I had the <?php tag indented by 8 tabs, all the compressed html after the php tag is indented with 8 tabs too).

**Comment by anseki** [comment]
Hi @trompx, thank you for the comment.

That seems correct behavior because htmlclean should remove unneeded whitespaces.
Web browsers ignore whitespaces between block elements such as `<div>`, and htmlclean removes those correctly.
See: https://github.com/anseki/htmlclean
If you replace the nested `<div>` with `<span>`, the whitespaces are kept.

And also, your HTML is incorrect (elements are not closed correctly), htmlclean and other programs such as web browsers may not be able to parse those.
See: https://github.com/anseki/htmlclean#malformed-nested-tags-and-close-tags-in-script

htmlclean tries to remove unneeded whitespaces. Therefore, the space is removed correctly if `<span class="dynamic">` is empty when the source was given to htmlclean.
Insert something in `<span class="dynamic">` like `<span class="dynamic">|</span>` to indicate that it is not empty.

**Comment by trompx** [comment]
Hey @anseki,

Thanks for the answer, I would not rather put any character until user input.
My bad I forgot to add the closing div but they are well present in my code.

Looks like I will have to add css margin to overcome this.

**Comment by anseki** [comment]
You can specify [`protect`](https://github.com/anseki/htmlclean#protect) option for your special rule.

**Comment by anseki** [comment]
Unfortunately, no reply came, and I close this issue.
